nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./sites:/etc/nginx/html
  links:
    - node

node:
  image: node
  ports:
    - "3000:3000"
  volumes:
    - ./sites:/usr/src/app
