nginx:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./sites:/etc/nginx/html
    - ./etc/nginx:/etc/nginx
  links:
    - node
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"

node:
  build: .
  dockerfile: /etc/docker/DockerfileNode
  ports:
    - "3000:3000"
  volumes:
    - ./sites:/src
  log_driver: "json-file"
  log_opt:
    max-size: "16k"
    max-file: "2"
